"""
improvement_store.py — SQLite persistence for self-heal improvement proposals.

All methods are synchronous (blocking) — callers must wrap in asyncio.to_thread().
"""
from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


_STOP_WORDS = frozenset({
    "a", "an", "the", "in", "on", "at", "to", "for", "of", "and", "or",
    "is", "are", "was", "with", "from", "by", "be", "add", "use", "make",
    "fix", "update", "improve", "change", "too", "low", "high", "via",
})


def _significant_words(text: str) -> set[str]:
    """Return the set of meaningful words from a title (strips stop words, short tokens)."""
    return {w for w in text.split() if len(w) > 2 and w not in _STOP_WORDS}


_SCHEMA = """
CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS improvements (
    id TEXT PRIMARY KEY,
    analysis_id TEXT NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    severity TEXT NOT NULL,
    rationale TEXT NOT NULL,
    affected_files TEXT DEFAULT '[]',
    suggested_diff TEXT DEFAULT '',
    data_sources TEXT DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'pending',
    status_message TEXT DEFAULT '',
    files_modified TEXT DEFAULT '[]',
    execution_log TEXT DEFAULT '',
    proposed_at TEXT NOT NULL,
    decided_at TEXT DEFAULT '',
    completed_at TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_improvements_status ON improvements(status);
CREATE INDEX IF NOT EXISTS idx_improvements_analysis ON improvements(analysis_id);
"""


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


class ImprovementStore:
    """Persistent store for improvement proposals generated by self-heal analysis."""

    def __init__(self, db_path: Path = Path("data/improvements.db")) -> None:
        self._db_path = db_path

    def init(self) -> None:
        """Create the database directory and tables if they don't exist."""
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as conn:
            conn.executescript(_SCHEMA)

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(str(self._db_path))
        conn.row_factory = sqlite3.Row
        return conn

    def _row_to_dict(self, row: sqlite3.Row) -> dict:
        d = dict(row)
        for field in ("affected_files", "data_sources", "files_modified"):
            raw = d.get(field, "[]")
            try:
                d[field] = json.loads(raw) if raw else []
            except (json.JSONDecodeError, TypeError):
                d[field] = []
        return d

    def insert(self, proposal: dict) -> dict:
        """Insert a new improvement proposal and return the stored dict."""
        now = _now_iso()
        row = {
            "id":             proposal["id"],
            "analysis_id":    proposal.get("analysis_id", ""),
            "title":          proposal.get("title", ""),
            "category":       proposal.get("category", "feature"),
            "severity":       proposal.get("severity", "low"),
            "rationale":      proposal.get("rationale", ""),
            "affected_files": json.dumps(proposal.get("affected_files", [])),
            "suggested_diff": proposal.get("suggested_diff", ""),
            "data_sources":   json.dumps(proposal.get("data_sources", [])),
            "status":         proposal.get("status", "pending"),
            "status_message": proposal.get("status_message", ""),
            "files_modified": json.dumps(proposal.get("files_modified", [])),
            "execution_log":  proposal.get("execution_log", ""),
            "proposed_at":    proposal.get("proposed_at", now),
            "decided_at":     proposal.get("decided_at", ""),
            "completed_at":   proposal.get("completed_at", ""),
        }
        with self._connect() as conn:
            conn.execute(
                """
                INSERT OR IGNORE INTO improvements
                    (id, analysis_id, title, category, severity, rationale,
                     affected_files, suggested_diff, data_sources, status,
                     status_message, files_modified, execution_log,
                     proposed_at, decided_at, completed_at)
                VALUES
                    (:id, :analysis_id, :title, :category, :severity, :rationale,
                     :affected_files, :suggested_diff, :data_sources, :status,
                     :status_message, :files_modified, :execution_log,
                     :proposed_at, :decided_at, :completed_at)
                """,
                row,
            )
        return self.get(row["id"]) or proposal

    def get(self, id: str) -> Optional[dict]:
        """Return a single improvement by id, or None if not found."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM improvements WHERE id = ?", (id,)
            ).fetchone()
        return self._row_to_dict(row) if row else None

    def list_all(self, status: str = "", limit: int = 200) -> list[dict]:
        """Return improvements ordered by proposed_at descending."""
        with self._connect() as conn:
            if status:
                rows = conn.execute(
                    "SELECT * FROM improvements WHERE status = ? ORDER BY proposed_at DESC LIMIT ?",
                    (status, limit),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM improvements ORDER BY proposed_at DESC LIMIT ?",
                    (limit,),
                ).fetchall()
        return [self._row_to_dict(r) for r in rows]

    def update_status(
        self,
        id: str,
        status: str,
        message: str = "",
        files_modified: Optional[list] = None,
        execution_log: str = "",
        completed_at: str = "",
    ) -> None:
        """Update the status (and optional metadata) of an improvement."""
        now = _now_iso()
        decided_at = now if status in ("approved", "rejected") else ""
        if not completed_at and status in ("completed", "failed"):
            completed_at = now

        with self._connect() as conn:
            conn.execute(
                """
                UPDATE improvements
                SET status = ?,
                    status_message = ?,
                    files_modified = ?,
                    execution_log = ?,
                    decided_at = CASE WHEN ? != '' THEN ? ELSE decided_at END,
                    completed_at = CASE WHEN ? != '' THEN ? ELSE completed_at END
                WHERE id = ?
                """,
                (
                    status,
                    message,
                    json.dumps(files_modified or []),
                    execution_log,
                    decided_at, decided_at,
                    completed_at, completed_at,
                    id,
                ),
            )

    # ── Analysis cursor ────────────────────────────────────────────────────

    def get_last_analyzed_at(self) -> Optional[str]:
        """Return the ISO timestamp of the last completed analysis, or None."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT value FROM meta WHERE key = 'last_analyzed_at'"
            ).fetchone()
        return row["value"] if row else None

    def set_last_analyzed_at(self, ts: str) -> None:
        """Persist the timestamp of the latest completed analysis."""
        with self._connect() as conn:
            conn.execute(
                "INSERT OR REPLACE INTO meta (key, value) VALUES ('last_analyzed_at', ?)",
                (ts,),
            )

    def get_open_summaries(self) -> list[dict]:
        """Return id, title, category, severity, status for all open (non-terminal) improvements."""
        with self._connect() as conn:
            rows = conn.execute(
                """SELECT id, title, category, severity, status
                   FROM improvements
                   WHERE status NOT IN ('rejected', 'completed')
                   ORDER BY proposed_at DESC"""
            ).fetchall()
        return [dict(r) for r in rows]

    def has_similar(self, title: str) -> bool:
        """Return True if a sufficiently similar improvement already exists
        and is not in rejected or completed status.

        Matching logic (both must pass for a match):
        - Exact case-insensitive title match, OR
        - Word-overlap ≥ 60 % of the shorter title's significant words
        """
        title_lower = title.lower().strip()
        title_words = _significant_words(title_lower)

        with self._connect() as conn:
            rows = conn.execute(
                "SELECT title FROM improvements WHERE status NOT IN ('rejected', 'completed')"
            ).fetchall()
        for row in rows:
            existing = row["title"].lower().strip()
            if existing == title_lower:
                return True
            existing_words = _significant_words(existing)
            if not title_words or not existing_words:
                continue
            shorter = min(len(title_words), len(existing_words))
            overlap = len(title_words & existing_words)
            if overlap / shorter >= 0.6:
                return True
        return False

    def get_stats(self) -> dict:
        """Return counts of improvements grouped by status."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT status, COUNT(*) as cnt FROM improvements GROUP BY status"
            ).fetchall()
        stats = {
            "pending": 0,
            "approved": 0,
            "rejected": 0,
            "executing": 0,
            "completed": 0,
            "failed": 0,
            "total": 0,
        }
        for row in rows:
            status = row["status"]
            cnt = row["cnt"]
            stats[status] = stats.get(status, 0) + cnt
            stats["total"] += cnt
        return stats
